-- begin IMAPSAMPLE_IMAP_MESSAGE
alter table IMAPSAMPLE_IMAP_MESSAGE add constraint FK_IMAPSAMPLE_IMAP_MESSAGE_MAIL_BOX foreign key (MAIL_BOX_ID) references MAILCOMPONENT_IMAP_MAIL_BOX(ID)^
create index IDX_IMAPSAMPLE_IMAP_MESSAGE_MAIL_BOX on IMAPSAMPLE_IMAP_MESSAGE (MAIL_BOX_ID)^
-- end IMAPSAMPLE_IMAP_MESSAGE
